### ISSUE TITLE
Add file coverage in preprocesing step

### ISSUE THREAD

**Issue by eddieantonio** [mdfeist/TypeV#11]
1. Calculate total number of files used
2. For each column, calculate the number files used
3. Get a percentage

**Comment by eddieantonio** [comment]
@mdfeist For 2. we should probably calculate all the files _currently_ in the repository. Is this easily doable?

**Comment by mdfeist** [comment]
For 2. Why do we need to calculate all the files and not just the ones edited? And no not really. Git only really shows us the edited files in a commit.

**Comment by eddieantonio** [comment]
I don't think I understand file coverage then... is it files changed per author per timeslice?

**Comment by mdfeist** [comment]
It's the set of all files changed by authors in a time slice versus the set of all files over the entire span of the project.

(sum of files changed in current time slice) / (sum of files in project)

Since a file can not be in the project unless it was touched we have all the files ever used in the project.

**Comment by eddieantonio** [comment]
Yes. But should it not be:

(sum of files changed in current time slice) / (sum of files in project _at this timeslice_)?

Because if it's over all files, ever while we're calculating a single timeslice, that's mixed...

**Comment by mdfeist** [comment]
I don't have that data. We have the commit id's so we could have a script run git ls-tree and list all the files at that time.

**Comment by mdfeist** [comment]
Added all files to json commit.

**Comment by eddieantonio** [comment]
This is done as of 588e4468e6bdc77630e732dab57211b91c02e42c, and as a bonus, it generates CSV with type AND file coverage!
