### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/TypeV#14]
I was thinking MIT, any objections?

**Comment by eddieantonio** [comment]
@abramhindle prefers Apache to MIT, due to [its patent indemnity clause](http://choosealicense.com/licenses/apache-2.0/). I generally choose Apache whenever I want a permissive license.

**Comment by mdfeist** [comment]
That's fine. I just didn't want to go with GNU.

**Comment by eddieantonio** [comment]
Haha, same!

**Comment by mdfeist** [comment]
Spoon has the following license:
https://github.com/INRIA/spoon/blob/master/LICENSE.txt

And gumtree has:
https://github.com/GumTreeDiff/gumtree/blob/develop/LICENSE

Just making sure the Apache doesn't interfere with any of them.

**Comment by eddieantonio** [comment]
So glad we're only _linking_ to [GumTree](https://github.com/mdfeist/TypeV/blob/master/gumtree-spoon-ast-diff/pom.xml#L79); under the terms of the LGPL, we don't have to GPL our code as well.

**Comment by eddieantonio** [comment]
Oh crap. The [CeCILL license](https://en.wikipedia.org/wiki/CeCILL) is like a French version of GPL _without_ the aforementioned linking exception...  @abramhindle, your advice?
