### ISSUE TITLE
Add Overall Project Stats

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/TypeV#7]
I was thinking of the following:
- # of Declarations
- # of Invocations
- # of types used in project vs # of types used in time period
- # of Authors
- Average declarations per Author
- Average invocations per Author
- Type coverage for authors (so percentage)
- Average/Min/Max type coverage for authors

I was just going to try and calculate it in the JS.

**Comment by mdfeist** [comment]
@watts1 Take a look at the example json, project_view.html, and generate_table.js

**Comment by eddieantonio** [comment]
- [x] Add overview plot
- [x] Add cumulative types graph
- [x] Add cumulative files graph
- [ ] ~~Correlation between two metrics~~

**Comment by eddieantonio** [comment]
This is (mostly) done as of 88ef65b.
